id: IAB2E5954
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T20:08:29+00:00'
last_modified: '2022-06-09T07:44:17.992686+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W759
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    909E:
      image_group_id: I2837
      title: ''
      total_pages: 536
      order: 1
      base_file: 909E.txt
    8A95:
      image_group_id: I2838
      title: ''
      total_pages: 538
      order: 2
      base_file: 8A95.txt
    D268:
      image_group_id: I2839
      title: ''
      total_pages: 568
      order: 3
      base_file: D268.txt
    9B36:
      image_group_id: I2840
      title: ''
      total_pages: 524
      order: 4
      base_file: 9B36.txt
    C30E:
      image_group_id: I2841
      title: ''
      total_pages: 518
      order: 5
      base_file: C30E.txt
    AF99:
      image_group_id: I3JW3517
      title: ''
      total_pages: 536
      order: 6
      base_file: AF99.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
