id: IAB2E5954
legacy_id: P007937
ocr_import_info:
  bdrc_scan_id: W759
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T20:05:29'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:15:48.270516+00:00'
last_modified: 2022-09-04 11:16:11.207116
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W759
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW759
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ།
  author: དགེ་འདུན་གྲུབ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.690458507487094
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I2839:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2839
      total_pages: 568
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I2839.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9513513587952197
    legacy_id: v003
  I2838:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2838
      total_pages: 538
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I2838.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9487567638827337
    legacy_id: v002
  I2837:
    source_metadata:
      id: http://purl.bdrc.io/resource/I2837
      total_pages: 536
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I2837.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9504684757877577
    legacy_id: v001
  I3JW3517:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3JW3517
      total_pages: 536
      volume_number: 6
    order: 6
    base_file: I3JW3517.txt
    statistics:
      ocr_word_median_confidence_index: 0.7699999809265137
      ocr_word_mean_confidence_index: 0.6816012295110068
    legacy_id: v006
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
