id: P007937
initial_creation_type: ocr
source_metadata:
  id: bdr:W759
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ
  author: ''
  volumes:
    4ae172aa15aa4e8b86212d7fa1decfd4:
      image_group_id: I2837
      title: ''
      volume_number: 1
      total_pages: 536
    df036d93fd174f1299bb9d3cc3de8fe0:
      image_group_id: I2838
      title: ''
      volume_number: 2
      total_pages: 538
    ac55419445c747efa0c82d264f05020d:
      image_group_id: I2839
      title: ''
      volume_number: 3
      total_pages: 568
    dd8c2568c81840bcadcefd8549e784c3:
      image_group_id: I2840
      title: ''
      volume_number: 4
      total_pages: 524
    9baa8bcf7c4343849673747b48533d67:
      image_group_id: I2841
      title: ''
      volume_number: 5
      total_pages: 518
    48004ec6ca284f2092c73023a200fe00:
      image_group_id: I3JW3517
      title: ''
      volume_number: 6
      total_pages: 536
      base_file: v006.txt
ebook_metadata:
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ
  author: ''
  sku: P007937
  cover: cover.jpg
  layers:
  - pagination
