id: P007937
initial_creation_type: ocr
source_metadata:
  id: bdr:W759
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ
  author: ''
  volumes:
    fc3b86ec43de4441910f45e9cc91084d:
      image_group_id: I2837
      title: ''
      volume_number: 1
      total_pages: 536
      base_file: v001.txt
    9a73998a73d6484da7ebaad6b4717d67:
      image_group_id: I2838
      title: ''
      volume_number: 2
      total_pages: 538
      base_file: v002.txt
    e0531ff415ea475c97b6baa450d0fdfe:
      image_group_id: I2839
      title: ''
      volume_number: 3
      total_pages: 568
      base_file: v003.txt
    30506ba23e88448384431a168a106077:
      image_group_id: I2840
      title: ''
      volume_number: 4
      total_pages: 524
      base_file: v004.txt
    5b116b1148ab440a8c89f3e464ef5ec4:
      image_group_id: I2841
      title: ''
      volume_number: 5
      total_pages: 518
      base_file: v005.txt
    02fa068efa834aa5b7e2cd0e0407939c:
      image_group_id: I3JW3517
      title: ''
      volume_number: 6
      total_pages: 536
ebook_metadata:
  title: གསུང་འབུམ། དགེ་འདུན་གྲུབ་པ
  author: ''
  sku: P007937
  cover: cover.jpg
  layers:
  - pagination
